image: node:lts

stages:
  - build
  - test
  - staging

include:
  - template: Code-Quality.gitlab-ci.yml

build:
  stage: build
  before_script:
    - yarn install
  script:
    - echo "Start building App"
    - yarn build
    - echo "Build successful!"
  only:
    - merge_requests
    - master
  artifacts:
    expire_in: 5 minutes
    paths:
      - node_modules

test:
  stage: test
  script:
    - echo "Testing App"
    - CI=true yarn test --coverage --coverageReporters="text" --coverageReporters="cobertura"
    - echo "Test succesful!"
  only:
    - merge_requests
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml

code_quality:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH' # Run code quality job in pipelines on the master branch (but not in other branch pipelines)
  artifacts:
    reports:
      codequality: gl-code-quality-report.json

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: https://$HEROKU_FRONT_END_APP_NAME.herokuapp.com/
  only:
    - master
