import { BillingReportData, SalaryReportData } from '../common/types'

export const billingReportData: BillingReportData = {
  startDate: '2021-01-01',
  endDate: '2021-01-31',
  created: 1612329726188,
  billable: true,
  nonBillable: true,
  client: {
    id: '1',
    name: 'Client 1',
  },
  projects: [
    {
      id: '1',
      name: 'Bytecraft Timesheets project',
      description: 'Bytecraft Timesheets project',
      billable: true,
      projectTotal: 4500,
      projectTotalCost: {
        value: 899.64,
        currency: 'EUR',
      },
      employees: [
        {
          id: '3',
          username: 'dev3',
          firstName: 'Some',
          lastName: 'Developer',
          timeInputs: [
            {
              id: '1',
              date: '2021-01-01',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '2',
              date: '2021-01-02',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '3',
              date: '2021-01-03',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '4',
              date: '2021-01-04',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '5',
              date: '2021-01-05',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
          ],
          employeeTotal: 2250,
          employeeTotalCost: {
            value: 299.88,
            currency: 'EUR',
          },
        },
        {
          id: '4',
          username: 'dev4',
          firstName: 'Another',
          lastName: 'Developer',
          timeInputs: [
            {
              id: '1',
              date: '2021-01-01',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '2',
              date: '2021-01-02',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '3',
              date: '2021-01-03',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '4',
              date: '2021-01-04',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '5',
              date: '2021-01-05',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
          ],
          employeeTotal: 2250,
          employeeTotalCost: {
            value: 299.88,
            currency: 'EUR',
          },
        },
      ],
    },
    {
      id: '2',
      name: 'Another project',
      description: 'Just a random dummy project',
      billable: true,
      projectTotal: 4567,
      projectTotalCost: {
        value: 899.64,
        currency: 'EUR',
      },
      employees: [
        {
          id: '3',
          username: 'dev3',
          firstName: 'Some',
          lastName: 'Developer',
          timeInputs: [
            {
              id: '1',
              date: '2021-01-01',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '2',
              date: '2021-01-02',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '3',
              date: '2021-01-03',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '4',
              date: '2021-01-04',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '5',
              date: '2021-01-05',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
          ],
          employeeTotal: 2250,
          employeeTotalCost: {
            value: 299.88,
            currency: 'EUR',
          },
        },
        {
          id: '4',
          username: 'dev4',
          firstName: 'Another',
          lastName: 'Developer',
          timeInputs: [
            {
              id: '1',
              date: '2021-01-01',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '2',
              date: '2021-01-02',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '3',
              date: '2021-01-03',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '4',
              date: '2021-01-04',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '5',
              date: '2021-01-05',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
          ],
          employeeTotal: 2250,
          employeeTotalCost: {
            value: 299.88,
            currency: 'EUR',
          },
        },
      ],
    },
  ],
  grandTotal: 12345,
  grandTotalCost: {
    value: 1799.28,
    currency: 'EUR',
  },
}

export const salaryReportData: SalaryReportData = {
  startDate: '2021-01-01',
  endDate: '2021-01-31',
  created: 1612329726188,
  billable: true,
  nonBillable: true,
  employee: {
    id: '3',
    username: 'dev3',
    firstName: 'Some',
    lastName: 'Developer',
    isManager: false,
  },
  clients: [
    {
      id: '1',
      name: 'Client 1',
      clientTotal: 50,
      clientTotalCost: {
        value: 949.62,
        currency: 'EUR',
      },
      projects: [
        {
          id: '1000',
          name: 'Projekti 1',
          projectTotal: 35,
          projectTotalCost: {
            value: 474.81,
            currency: 'EUR',
          },
          timeInputs: [
            {
              id: '1',
              date: '2021-01-01',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '2',
              date: '2021-01-02',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '3',
              date: '2021-01-03',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '4',
              date: '2021-01-04',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '5',
              date: '2021-01-05',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
          ],
        },
        {
          id: '1002',
          name: 'Projekti 2',
          projectTotal: 10,
          projectTotalCost: {
            value: 474.81,
            currency: 'EUR',
          },
          timeInputs: [
            {
              id: '1',
              date: '2021-01-01',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '2',
              date: '2021-01-02',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '3',
              date: '2021-01-03',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '4',
              date: '2021-01-04',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '5',
              date: '2021-01-05',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
          ],
        },
      ],
    },
    {
      id: '2',
      name: 'Client 2',
      clientTotal: 100,
      clientTotalCost: {
        value: 949.62,
        currency: 'EUR',
      },
      projects: [
        {
          id: '1003',
          name: 'Projekti B',
          projectTotal: 100,
          projectTotalCost: {
            value: 474.81,
            currency: 'EUR',
          },
          timeInputs: [
            {
              id: '1',
              date: '2021-01-01',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '2',
              date: '2021-01-02',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '3',
              date: '2021-01-03',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '4',
              date: '2021-01-04',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
            {
              id: '5',
              date: '2021-01-05',
              description: 'koodailua',
              input: 450,
              created: 100,
              edited: 100,
              cost: {
                value: 49.98,
                currency: 'EUR',
              },
            },
          ],
        },
      ],
    },
  ],

  grandTotal: 12345,
  grandTotalCost: {
    value: 1424.43,
    currency: 'EUR',
  },
}
